### ISSUE TITLE
What would be the best way to go about making this lib compile on Mac/Linux

### ISSUE THREAD

**Issue by roomofdoom** [HeliosInteractive/SmartCardReader.node#7]
Hi, 

I'm trying to use SmartCardReader.node for a Electron based app - works great on Windows but I would like to be able to build the module on Mac/Linux (no functionality, just pass the build).

I was wondering how to make the build pass at least when running `npm install ` on my project.  It can basically just be an empty dummy module since I don't include the module when not on Windows.

I don't have much experience with node-gyp or yet, can you give me some pointers on how to achieve this?

Regards,

EDIT - this seems to work:

```
{
    'targets': [
        {"target_name": "SmartCardReaderDummy",
        }
    ],
    'conditions': [
      ['OS=="win"',
        {
          "targets": [
            {
              "target_name": "SmartCardReader",

              "sources": [
                "include/SmartCardReader.hh",
                "source/SmartCardReader.cc",
                "include/SmartCardWrapper.hh",
                "source/SmartCardWrapper.cc",
                "source/SmartCardModule.cc"
              ],
              "libraries" : [
                "Winscard.lib"
              ],
              "defines": [
                "WIN32_LEAN_AND_MEAN",
                "VC_EXTRALEAN",
                "NOMINMAX"
              ],
              "include_dirs": [
                "<!(node -e \"require('nan')\")",
                "include"
              ],
            }
          ]
        }
      ]]
}
```

**Comment by mneil** [comment]
I'm glad you found a workaround. This is a windows only module and we did not have any need to compile or use it on linux. I can see the usefulness though in ignoring it in linux builds.
